<style>
div.logo{font-size:13px;}
  div.logo > img {height: 60px;text-align:center; width:120px;}
   
  
  .odd {background-color: #F5F5F5;}
  .even {background-color: white;}
  .lblmsg{ font-size: 20px;}
  .text_title{font-size: 14px;padding:3px;}

@media print{  
    @page { size: A4 portrait; }
    .pagebreak { page-break-after: always; }
}
</style>

<!-- <div class="logo"><img class="logo" src="<?=@$logo?>" /></div> -->



<!--<h1>Material Order Summary</h1>-->
  <?php 
  $count=0;
  foreach($uploaded_data as $row){
      if($count%2==0)
      {
  ?>  
     <?php if($count!=0){?>
     <div style="page-break-after: always;">&nbsp;</div>
     <?php }?>
     <table border="0" cellspacing="0" cellpadding="0" width='800' align="center">
      <tr valign='bottom'>
        <td align="left">
          <div class="logo"><img class="logo" src="<?=@$logo?>" /></div>
        </td>
        <td align="center">
          <div class="logo">
          <?=$address?><br>
          <?=$city_state?><br>
          <?php if($policy){?>
          Policy Number:<?=$policy?><br>
          <?php }?>
          <?php if($claim){?>
          Claim Number: <?=$claim?>
          <?php }?>
          </div>
        </td>
      </tr>
      <tr valign='bottom'>
    </table>
    <?php }?>
<br>
<br>
<table border="0" cellspacing="0" cellpadding="0" width='800' align="center"> 
      <tr>
        <td>
            <table width="100%"  border="0" >
            
                 <tr>
                      <td align="center">
                          <img height="300" src="<?=$row['file_url']?>" />
                          <br><span class="text_title"><?=$row['file_name']?></span>

                      </td>
                  </tr>
        
            </table>
        </td>
    </tr>
</table>

<?php 

$count++;
}?>
     <br />
    <table border="0" width='800' align="center">
      <tr>
        <td style='font-size: 12px;'>
          <center>Generated by <b><?=$salesman?></b></center>
        </td>
      </tr>
    </table>
