<?php

include '../common_lib.php'; 
if(!ModuleUtil::checkAccess('job_material_sheet'))
  die("Insufficient Rights");

echo ViewUtil::loadView('doc-head');

$myJob = new Job(RequestUtil::get('id'));

if(moduleOwnership('job_material_sheet') && (!JobUtil::isSubscriber($myJob->job_id) && $myJob->salesman_id!=$_SESSION['ao_userid'] && $myJob->user_id!=$_SESSION['ao_userid']))
  die("Insufficient Rights");

ob_start();
?>
    <table border="0" cellspacing="0" cellpadding="0" width='800' align="center">
<?php
$mySheet = new Sheet($myJob->job_id);
?>
      <tr valign='bottom'>
        <td style='font-size: 35px; font-weight: bold;' align="right">Material Order Summary</td>
      </tr>
    </table>
    <br><br>
    <table width='800' align="center"  cellspacing="0" cellpadding="0">
      <tr>
        <td style='border: 1px solid black;'>
          <table border="0" width="100%" style='font-size: 16px; font-weight: bold;'>
            <tr>
              <td>Item</td>
              <td width=200>Manufacturer</td>
              <td width=200>Color</td>
            </tr>
          </table>
        </td>
      </tr>
      <tr height=400 valign='top'>
        <td style='border-left: 1px solid black; border-bottom: 1px solid black; border-right: 1px solid black;'>
          <table border="0" width="100%" cellpadding=2 cellspacing="0">
<?php
$sql = "select materials.material, brands.brand, colors.color".
       " from materials, brands, sheet_items".
       " left join colors on (sheet_items.color_id=colors.color_id)".
       " where materials.brand_id=brands.brand_id and sheet_items.material_id=materials.material_id and sheet_items.sheet_id='".$mySheet->sheet_id."' group by materials.material order by sheet_items.sheet_id asc";

$res = DBUtil::query($sql);

$i=1;
$total_qty=0;
while(list($material, $brand, $color)=mysqli_fetch_row($res))
{
  $class='odd';
  if($i%2==0)
    $class='even';

  $material = stripslashes($material);
?>
            <tr class='<?php echo $class; ?>'>
              <td><b><?php echo $material; ?></b></td>
              <td width=200><?php echo $brand; ?></td>
              <td width=200><?php echo $color; ?></td>
            </tr>
<?php
  $i++;
  $total_qty++;
}
?>
          </table>
        </td>
      </tr>
      <tr valign='top'>
        <td style='border-left: 1px solid black; border-bottom: 1px solid black; border-right: 1px solid black;'>
          <table border="0" width="100%" cellspacing="0" cellpadding=2>
            <tr class='odd'>
              <td width=60 align="center" style='font-size: 16px;'><b><?php echo $total_qty; ?></b></td>
              <td style='font-size: 16px;'>Total Items</td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
    <br /><br />
    <table border="0" width='800' align="center">
      <tr>
        <td>
          <center>Generated by <b><?=APP_NAME?></b></center>
        </td>
      </tr>
    </table>
<script>
    $(document).ready(function(){
        window.print();
    });
</script>
</body>
</html>
<?php

$str = ob_get_clean();
echo $str;

/*$file = time().'.doc';
touch($file);
$fh = fopen($file,'w');
fwrite($fh,$str);
fclose($fh);*/

/*
$to = 'cbm3384@gmail.com';
$subject = 'Material Order';
$headers = "MIME-Version: 1.0\r\n";
$headers .= "Content-type: text/html; charset=iso-8859-1\r\n";
$headers  .= "From: ".$from_email." \r\n";

mail($to, $subject, $str, $headers);
*/
?>
