<?php 
include '../common_lib.php'; 
$iws_base_path = '/workflow/contact';
if(!ModuleUtil::checkAccess('invoice_readwrite')) {
    die('Insufficient Rights');
}
echo ViewUtil::loadView('doc-head');
$myJob = new Job(RequestUtil::get('id'));
ModuleUtil::checkJobModuleAccess('invoice_readwrite', $myJob, TRUE, TRUE);
$myCustomer = new Customer($myJob->customer_id);



$pitch = $_GET['pitch'];
$overhang = $_GET['overhang'];
$wall = $_GET['wall'];
$interior_wall = $_GET['interior_wall'];        

$iws = ($overhang + $wall + $interior_wall)*$pitch;

$roll_value = (int)($iws/36) + 1;
$final = ($iws%36==0)?$iws:($roll_value*36);


?>
<table border="0" cellspacing="0" cellpadding="0" width="800" align="center">

    <tr valign="center">

        <td align="center" style="font-size: 25px;">Ice and Water Shield Calculator</td>


    </tr>

</table>

<table border="0" cellspacing="0" cellpadding="0" width="800" align="center">
    <tr valign='bottom'>
        <td align="left">
            <img width="300" src="<?=$iws_base_path?>/images/top.jpg" style="width: 100%; border: 1px solid;">
        </td>
    </tr>
</table>
<br /><br />
<table border="0" cellspacing="0" cellpadding="0" width="800" align="center">

    <tr valign='top'>
        <td style='border: 1px solid black;'>
            <table border="0" width="100%" cellpadding=2 cellspacing="0">
                <tr>
                    <td>Pitch</td>
                    <td><?=$pitch?></td>
                    <td>Ice and Water Shield</td>
                </tr>
                <tr>
                    <td>Overhang</td>
                    <td><?=$overhang?></td>
                    <td><?=$iws?> inches</td>
                </tr>
                <tr>
                    <td>Wall</td>
                    <td><?=$wall?></td>
                    <td>So you would need:</td>
                </tr>
                <tr>
                    <td>Interior Wall</td>
                    <td><?=$interior_wall?></td>
                    <td><?=$final?> inches</td>
                </tr>
            </table>
        </td>
    </tr>

</table>
<br /><br />
<table border="0" width="800" align="center">
    <tr>
        <td>
            <center>Generated by <b><?php echo $myJob->salesman_fname." ".$myJob->salesman_lname; ?></b></center>
        </td>
    </tr>
</table>
<script>
    $(document).ready(function(){
        window.print();
    });
</script>
</body>
</html>
